---
- name: "Debian | Installing repository for Ubuntu"
  apt:
    deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb"
    state: present
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags:
    - zabbix-agent
    - packages

- name: "Debian | Installing repository for Debian"
  apt:
    deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb"
    state: present
  when: ansible_distribution == "Debian"
  become: yes
  tags:
    - zabbix-agent
    - packages

- name: "Debian | Instal zabbix-agent"
  apt:
    pkg: "{{ zabbix_agent_packages }}"
    state: present
    update_cache: yes
    #  cache_valid_time: 0
  become: yes
  check_mode: no
  tags:
    - zabbix-agent
    - packages

- name: "Install policycoreutils-python"
  apt:
    pkg: policycoreutils-python-utils
    state: present
    update_cache: yes
    cache_valid_time: 0
  become: yes
  tags:
    - zabbix-agent
    - packages
    - zabbix-agent-selinux
