---
- name: "RedHat | Install basic repo file"
  yum:
    name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}\
      /rhel/7/x86_64/zabbix-release-{{ zabbix_version }}-2.el7.noarch.rpm"
    state: present
  become: True
  when: ansible_distribution_major_version == '7'
  tags:
    - zabbix-agent
    - packages

- name: "RedHat | Install basic repo file"
  yum:
    name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}\
      /rhel/6/x86_64/zabbix-release-{{ zabbix_version }}-1.el6.noarch.rpm"
    state: present
  become: True
  when: ansible_distribution_major_version == '6'
  tags:
    - zabbix-agent
    - packages

- name: "RedHat | Install basic repo file"
  yum:
    name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}\
      /rhel/5/x86_64/zabbix-release-{{ zabbix_version }}-1.noarch.rpm"
    state: present
  become: True
  when: ansible_distribution_major_version == '5'
  tags:
    - zabbix-agent
    - packages

- name: "RedHat | Install zabbix-agent"
  package:
    pkg: "{{ item }}"
    state: present
  become: True
  with_items: "{{ zabbix_agent_packages }}"
  tags:
    - zabbix-agent
    - packages

- name: "RedHat | Add selinux support"
  include_tasks: selinux-support.yml
  when: zabbix_agent_selinux
