---
- name: install ansible selinux support library
  become: True
  package:
    name: libselinux-python
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success

- name: install ansible selinux configure libraries
  become: True
  package:
    name: "{{ item }}"
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success
  loop:
    - policycoreutils-python
    - libsemanage-python
  when: ansible_selinux.status == "enabled"

- name: "SELinux | Allow zabbix_agent to start"
  selinux_permissive:
    name: zabbix_agent_t
    permissive: True
  become: True
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode != "disabled"
