---
- name: "Installing repository for {{ ansible_distribution }}"
  apt:
    deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}\
      /{{ ansible_distribution|lower }}/pool/main/z/zabbix-release\
      /zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb"
    state: present
  when: ansible_distribution == "Ubuntu"
  become: True
  tags:
    - zabbix-agent
    - packages

- name: "Instal zabbix-agent"
  apt:
    pkg: "{{ zabbix_agent_packages }}"
    state: present
    update_cache: True
  become: True
  tags:
    - zabbix-agent
    - packages
