---
- name: "Install basic repo file"
  yum:
    name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}\
      /rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-\
      {{ zabbix_version }}-\
      {{ {'7': '2.el7.noarch.rpm', '6': '1.el6.noarch.rpm'}[ansible_distribution_major_version] }}"
    state: present
  become: True
  when: ansible_distribution_major_version == '7'
  tags:
    - zabbix-agent
    - packages

- name: "RedHat | Install zabbix-agent"
  yum:
    pkg: "{{ zabbix_agent_packages }}"
    state: present
  become: True
  tags:
    - zabbix-agent
    - packages
