---
- name: "Adding selinux support"
  include_tasks: selinux-support.yml

- name: "Install basic repo file"
  yum:
    name: "{{ zabbix_repository_url_rhel }}"
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success
  become: True
  when: ansible_distribution_major_version in ['7','6']

- name: "RedHat | Install zabbix-agent"
  yum:
    pkg: "{{ zabbix_agent_packages }}"
    state: present
  become: True
