---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-zabbix-agent
      vars:
        zabbix_agent_server: "test.zabbix.com"
        zabbix_agent_serveractive: "test.zabbix.com"
        zabbix_agent_hostmetadata: "test metadata"
